# =============================================================================== #
# Yazi Cli File Manager Theme:                                                    #
# =============================================================================== #
[mgr]
cwd = { fg = "#c4746e" }
hovered         = { reversed = true }
preview_hovered = { underline = true }
find_keyword  = { fg = "#7a8382", bold = true, italic = true, underline = true }
find_position = { fg = "#a292a3", bg = "reset", bold = true, italic = true }
marker_copied   = { fg = "#7a8382",  bg = "#8a9a7b" }
marker_cut      = { fg = "#c4746e",    bg = "#c4746e" }
marker_marked   = { fg = "#c4746e",   bg = "#c4746e" }
marker_selected = { fg = "#7a8382", bg = "#8a9a7b" }
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1
count_copied   = { fg = "#0d0c0c", bg = "#7a8382" }
count_cut      = { fg = "#0d0c0c", bg = "#c4746e" }
count_selected = { fg = "#0d0c0c", bg = "#7a8382" }
border_symbol = "│"
border_style  = { fg = "#252535" }
syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#0d0c0c", bg = "#101010" }
mode_normal = { bg = "#c4746e", bold = true }
mode_select = { bg = "#c4746e", bold = true }
mode_unset  = { bg = "#c4746e", bold = true }
progress_label  = { bold = true }
progress_normal = { fg = "#c4746e", bg = "#0d0c0c" }
progress_error  = { fg = "#c4746e", bg = "#0d0c0c" }
permissions_t = { fg = "#7a8382" }
permissions_r = { fg = "#7a8382" }
permissions_w = { fg = "#c4746e" }
permissions_x = { fg = "#c4746e" }
permissions_s = { fg = "#a6a69c" }

[select]
border   = { fg = "#c4746e" }
active   = { fg = "#a292a3", bold = true }
inactive = {}

[input]
border   = { fg = "#c4746e" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#c4746e" }
active   = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#c4746e" }
title   = {}
hovered = { fg = "#a292a3", underline = true }

[which]
cols            = 3
mask            = { bg = "#201d1d" }
cand            = { fg = "#c4746e" }
rest            = { fg = "#a6a69c" }
desc            = { fg = "#a292a3" }
separator       = "  "
separator_style = { fg = "#a6a69c" }

[help]
on      = { fg = "#c4746e" }
run     = { fg = "#a292a3" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#0d0c0c", bg = "#c4b28a" }

[notify]
title_info  = { fg = "#7a8382" }
title_warn  = { fg = "#7a8382" }
title_error = { fg = "#c4746e" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]
rules = [
	{ mime = "image/*", fg = "#c4746e" },
	{ mime = "{audio,video}/*", fg = "#7a8382" },
	{ mime = "application/*zip", fg = "#c4746e" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c4746e" },
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#c4746e" },
	{ name = "*", fg = "#7a8382" },
	{ name = "*/", fg = "#7a8382" }
]
